blank_issues_enabled: true
contact_links:
  - name: BitcoinPoW Security Policy
    url: https://github.com/btcw-space/BitcoinPoW/blob/HEAD/SECURITY.md
    about: View security policy
  - name: BitcoinPoW Developers
    url: https://btcw.space/
    about: BitcoinPoW homepage
